### ISSUE TITLE
Hope you help me

### ISSUE THREAD

**Issue by seven-echo** [shobeir/fakhraei_kdd2015#1]
Hi, shobeir,
Thanks for sharing this dataset on github -- it looks interesting!
However, the [URL]( https://linqs-data.soe.ucsc.edu/public/social_spammer/) of the dataset is invalid. Can I have any other ways to download the dataset? Thank you for your kind cooperation.Good luck and much happiness!
seven

**Comment by shobeir** [comment]
Thanks for your message. 
I just double checked the URL and downloaded the datasets:
https://linqs-data.soe.ucsc.edu/public/social_spammer/
Everything is working as expected.

**Comment by seven-echo** [comment]
Thanks for your generous help!
Everthing is working. I've already downloaded it.
Good luck.

**Comment by leeswan** [comment]
> Thanks for your generous help!
> Everthing is working. I've already downloaded it.
> Good luck.

hi, seven-echo, I can't  access the data url in China, could you share your data in other way, maybe onedrive/google drive,
Thanks a lot

**Comment by seven-echo** [comment]
> > Thanks for your generous help!
> > Everthing is working. I've already downloaded it.
> > Good luck.
> 
> hi, seven-echo, I can't access the data url in China, could you share your data in other way, maybe onedrive/google drive,
> Thanks a lot

Hi, there is a Baiduyun link for you to download the dataset.
link: https://pan.baidu.com/s/1B2MXqtlGtGZmBv49sy18rw 
key: ery7

**Comment by leeswan** [comment]
> > > Thanks for your generous help!
> > > Everthing is working. I've already downloaded it.
> > > Good luck.
> > 
> > 
> > hi, seven-echo, I can't access the data url in China, could you share your data in other way, maybe onedrive/google drive,
> > Thanks a lot
> 
> Hi, there is a Baiduyun link for you to download the dataset.
> link: https://pan.baidu.com/s/1B2MXqtlGtGZmBv49sy18rw
> key: ery7

Thank you very much!谢了，大兄得！
